config:
  compute_mode: record
  handler_type: radar
  strategy_type: plugin
  window_type: sliding
func_code: "def process(data, context=None):\n    return None\n"
metadata:
  bound_datasource_id: e626eecd0b86
  bound_datasource_ids:
  - e626eecd0b86
  category: 技术雷达
  compute_mode: record
  created_at: 1773675576.9554071
  description: 综合趋势和波动率多维度预警，提前提示市场风险和机会
  dictionary_profile_ids: []
  enabled: true
  func_code_file: ''
  handler_type: radar
  id: 40b54f75141b
  max_history_count: 200
  name: 早期预警系统
  source: file
  strategy_type: plugin
  tags:
  - river
  - warning
  - risk
  - radar
  updated_at: 1774627248.358755
  version: 129
  window_interval: 5s
  window_return_partial: false
  window_size: 5
  window_type: sliding
parameters:
  enabled: true
  max_history_count: 200
  window_interval: 5s
  window_size: 5
