import requests

# 定义要发送的token数据
token_data = {
    "token": "eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ1c2VyLWNlbnRlciIsImV4cCI6MTc0MDI5NTc3NywiaWF0IjoxNzMyNTE5Nzc3LCJqdGkiOiJjdDIyZW9ibjRpMms4dm5lY2U3MCIsInR5cCI6InJlZnJlc2giLCJhcHBfaWQiOiJraW1pIiwic3ViIjoiY25rYjNkZ25zbW1oODNqajM2ZzAiLCJzcGFjZV9pZCI6ImNua2IzZGduc21taDgzamozNmZnIiwiYWJzdHJhY3RfdXNlcl9pZCI6ImNua2IzZGduc21taDgzamozNmYwIiwic3NpZCI6IjE3MzEwODY0OTk5OTE1NzUzMDUiLCJkZXZpY2VfaWQiOiI3NDQxMTE1MTcyMDAyOTQzNzUzIn0.znTKVlsY0HdBv1qY1Zsxi5ro1oySveX03CB0rjhWjjGh6ICFrNQlziEF2dGoXPeBbOt81TQvlRqXb1CbMXXzVQ"
}

# 发送POST请求到指定URL
response = requests.post(
    "http://kimi.secsay.com/token/check",
    json=token_data
)

# 打印响应结果
print(response.status_code)
print(response.json())
